name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: 
    inputs:
      test_category:
        description: 'Run specific tests? (e.g. smoke, regression)'
        required: false
        default: 'all'
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build
      run: dotnet build

    - name: Install Playwright Browsers
      run: pwsh bin/Debug/net8.0/playwright.ps1 install --with-deps

    - name: Run Tests
      run: dotnet test --configuration Release --logger "trx;LogFileName=result.trx" --results-directory ./TestResults

    - name: Upload Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Complete-Test-Evidence
        path: |
          TestResults/*.*
          artifacts/*.*

    - name: Upload Pages Artifact
      if: always()
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'TestResults/'

  deploy:
    needs: test
    if: always()
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4